home/urls.py
from django.urls import path
from .views import HomeView

app_name = "home"

urlpatterns = [
    path("", HomeView.as_view(), name="home-view")
]

nnosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
import pandas as pd
import pickle
from django.views import View

# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs): 
        return render(request, "home/index.html")

    def post(self, request, *args, **kwargs):
        #Get user data from form
        gender = int(request.POST.get("gender"))
        age = int(request.POST.get("age"))
        hours_spent = int(request.POST.get("hours_spent"))
        tech_used = int(request.POST.get("tech_used"))

        #Open and load the trained model
        pickle_in = open("home/LnearRegressionModel.pickle", "rb")
        linear = pickle.load(pickle_in)

        #make predictions
        prediction = linear.predict(pd.DataFrame([[gender,age,hours_spent,tech_used]], columns=["Gender","Age","hours_spent","TECHNOLOGY"]))
        prediction_point = prediction[0]

        #Making classification
        if prediction_point >= 1.38:
            predict = "You are not Stressed"
        else:
            predict = "You are Stressed"
        
        #Passing the necessary information to the html file
        context = {
            "prediction_point":prediction_point,
            "predict":predict
        }
        return render(request, "home/result.html", context)

home/templates/home/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home:home-view' %}">TechnoStress-predictor</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home:home-view' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Result</a>
            </li>
          </ul>
        </div>
      </nav>

      <div style="margin: 20px;"></div>

      {% block body %}

      <div class="container">
        <form method="post">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="inputState">Gender</label>
              <select id="inputState" class="form-control" name="gender" required>
                <option value="">Choose...</option>
                <option value="0">Male</option>
                <option value="1">Female</option>
              </select>
            </div>
            <div class="form-group col-md-6">
              <label for="inputState">Age</label>
              <select id="inputState" class="form-control" name="age" required>
                <option value="">Choose...</option>
                <option value="1">18yrs - 28yrs</option>
                <option value="2">29yrs - 39yrs</option>
                <option value="3">40yrs - 49yrs</option>
                <option value="4">50yrs - 59yrs</option>
                <option value="5">60yrs - 69yrs</option>
              </select>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="inputState">Hours Spent</label>
              <select id="inputState" class="form-control" name="hours_spent" required>
                <option value="">Choose...</option>
                <option value="1">1hr - 3hrs</option>
                <option value="2">3hrs - 5hrs</option>
                <option value="3">5hrs - 7hrs</option>
                <option value="4">7hrs - 9hrs</option>
                <option value="5">9hrs - 12hrs</option>
              </select>
            </div>
            <div class="form-group col-md-6">
              <label for="inputState">Technology Used</label>
              <select id="inputState" class="form-control" name="tech_used" required>
                <option value="">Choose...</option>
                <option value="1">Phone</option>
                <option value="2">TV</option>
                <option value="3">Computer</option>
                <option value="4">Vehicle</option>
                <option value="5">Static Equipments</option>
                <option value="5">Dynamic Equipments</option>
                <option value="7">Other gadget</option>
              </select>
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Predict</button>
          </form>
      </div>

      {% endblock body %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/home/result.html
{% extends "home/index.html" %}

{% block body %}

<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Prediction Result</h1>
        <p class="lead">Prediction point: {{ prediction_point }}</p>
        <hr class="my-4">
        <p>Prediction: {{ predict }}</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="{% url 'home:home-view' %}" role="button">Make another prediction</a>
        </p>
    </div>
</div>

{% endblock body %}